const data = {
  vegetarian: true,
  vegan: true,
  glutenFree: true,
  dairyFree: true,
  veryHealthy: true,
  cheap: true,
  veryPopular: true,
  sustainable: true,
  lowFodmap: false,
  weightWatcherSmartPoints: 12,
  gaps: "no",
  preparationMinutes: -1,
  cookingMinutes: -1,
  aggregateLikes: 2,
  healthScore: 52,
  creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
  license: "CC BY 3.0",
  sourceName: "Foodista",
  pricePerServing: 439.95,
  extendedIngredients: [
    {
      id: 11265,
      aisle: "Produce",
      image: "portabello-mushrooms.jpg",
      consistency: "SOLID",
      name: "baby portabella mushrooms",
      nameClean: "portobello mushrooms",
      original: "12 Baby Portabella Mushrooms, sliced",
      originalName: "Baby Portabella Mushrooms, sliced",
      amount: 12,
      unit: "",
      meta: ["sliced"],
      measures: {
        us: {
          amount: 12,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 12,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 2015,
      aisle: "Spices and Seasonings",
      image: "curry-powder.jpg",
      consistency: "SOLID",
      name: "curry powder",
      nameClean: "curry powder",
      original: "3 tablespoons Dry Curry Powder",
      originalName: "Dry Curry Powder",
      amount: 3,
      unit: "tablespoons",
      meta: ["dry"],
      measures: {
        us: {
          amount: 3,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 3,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 2003,
      aisle: "Spices and Seasonings",
      image: "basil.jpg",
      consistency: "SOLID",
      name: "basil leaves",
      nameClean: "dried basil",
      original: "2 tablespoons Dried Basil Leaves",
      originalName: "Dried Basil Leaves",
      amount: 2,
      unit: "tablespoons",
      meta: ["dried"],
      measures: {
        us: {
          amount: 2,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
        metric: {
          amount: 2,
          unitShort: "Tbsps",
          unitLong: "Tbsps",
        },
      },
    },
    {
      id: 11209,
      aisle: "Produce",
      image: "eggplant.png",
      consistency: "SOLID",
      name: "eggplants",
      nameClean: "eggplant",
      original: "1 Eggplants",
      originalName: "Eggplants",
      amount: 1,
      unit: "",
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 1,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 11463,
      aisle: "Frozen",
      image: "spinach-frozen.jpg",
      consistency: "SOLID",
      name: "spinach",
      nameClean: "frozen spinach",
      original:
        "10 ounces Frozen chopped Spinach, with excess water squeezed out",
      originalName: "Frozen chopped Spinach, with excess water squeezed out",
      amount: 10,
      unit: "ounces",
      meta: ["frozen", "with excess water squeezed out", "chopped"],
      measures: {
        us: {
          amount: 10,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 283.495,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 1049,
      aisle: "Milk, Eggs, Other Dairy",
      image: "fluid-cream.jpg",
      consistency: "SOLID",
      name: "heavy cream",
      nameClean: "half and half",
      original: "1/2 cup Half & Half or Heavy Cream",
      originalName: "Half & Half or Heavy Cream",
      amount: 0.5,
      unit: "cup",
      meta: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 118.294,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 1001025,
      aisle: "Cheese",
      image: "shredded-cheese-white.jpg",
      consistency: "SOLID",
      name: "montery jack & cheddar cheese mix",
      nameClean: "monterey jack cheese",
      original: "12 ounces Montery Jack & Cheddar Cheese Mix",
      originalName: "Montery Jack & Cheddar Cheese Mix",
      amount: 12,
      unit: "ounces",
      meta: [],
      measures: {
        us: {
          amount: 12,
          unitShort: "oz",
          unitLong: "ounces",
        },
        metric: {
          amount: 340.194,
          unitShort: "g",
          unitLong: "grams",
        },
      },
    },
    {
      id: 11979,
      aisle: "Canned and Jarred;Produce;Ethnic Foods",
      image: "jalapeno-pepper.png",
      consistency: "SOLID",
      name: "jalapenos",
      nameClean: "jalapeno pepper",
      original: "2 Jalapenos, finely chopped",
      originalName: "Jalapenos, finely chopped",
      amount: 2,
      unit: "",
      meta: ["finely chopped"],
      measures: {
        us: {
          amount: 2,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 2,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 10111549,
      aisle: "Pasta and Rice",
      image: "tomato-sauce-or-pasta-sauce.jpg",
      consistency: "SOLID",
      name: "marinara sauce",
      nameClean: "marinara sauce",
      original:
        "3 cups Marinara Sauce (home made or a jar of 24 oz store bought)",
      originalName: "Marinara Sauce (home made or a jar of 24 oz store bought)",
      amount: 3,
      unit: "cups",
      meta: ["store bought", "(home made or a jar of 24 oz )"],
      measures: {
        us: {
          amount: 3,
          unitShort: "cups",
          unitLong: "cups",
        },
        metric: {
          amount: 709.764,
          unitShort: "ml",
          unitLong: "milliliters",
        },
      },
    },
    {
      id: 1102047,
      aisle: "Spices and Seasonings",
      image: "salt-and-pepper.jpg",
      consistency: "SOLID",
      name: "salt & pepper",
      nameClean: "salt and pepper",
      original: "Salt & Pepper, to taste",
      originalName: "Salt & Pepper, to taste",
      amount: 6,
      unit: "servings",
      meta: ["to taste"],
      measures: {
        us: {
          amount: 6,
          unitShort: "servings",
          unitLong: "servings",
        },
        metric: {
          amount: 6,
          unitShort: "servings",
          unitLong: "servings",
        },
      },
    },
    {
      id: 11507,
      aisle: "Produce",
      image: "sweet-potato.png",
      consistency: "SOLID",
      name: "sweet potatoes",
      nameClean: "sweet potato",
      original: "4 Sweet Potatoes",
      originalName: "Sweet Potatoes",
      amount: 4,
      unit: "",
      meta: [],
      measures: {
        us: {
          amount: 4,
          unitShort: "",
          unitLong: "",
        },
        metric: {
          amount: 4,
          unitShort: "",
          unitLong: "",
        },
      },
    },
    {
      id: 4669,
      aisle: "Oil, Vinegar, Salad Dressing",
      image: "vegetable-oil.jpg",
      consistency: "LIQUID",
      name: "vegetable cooking oil",
      nameClean: "vegetable oil",
      original: "1 tablespoon Canola or Vegetable Cooking Oil",
      originalName: "Canola or Vegetable Cooking Oil",
      amount: 1,
      unit: "tablespoon",
      meta: [],
      measures: {
        us: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
        metric: {
          amount: 1,
          unitShort: "Tbsp",
          unitLong: "Tbsp",
        },
      },
    },
  ],
  id: 647563,
  title: "How Sweet It Is Sweet Potato Lasagne",
  readyInMinutes: 45,
  servings: 6,
  sourceUrl:
    "http://www.foodista.com/recipe/LYPLYH8P/how-sweet-it-is-sweet-potato-lasagne",
  image: "https://spoonacular.com/recipeImages/647563-312x231.jpg",
  imageType: "jpg",
  summary:
    'How Sweet It Is Sweet Potato Lasagne is a main course that serves 6. For <b>$4.4 per serving</b>, this recipe <b>covers 44%</b> of your daily requirements of vitamins and minerals. One serving contains <b>501 calories</b>, <b>25g of protein</b>, and <b>24g of fat</b>. This recipe from Foodista has 2 fans. This recipe is typical of Mediterranean cuisine. It is a good option if you\'re following a <b>gluten free and lacto ovo vegetarian</b> diet. If you have eggplants, jalapenos, basil leaves, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes about <b>45 minutes</b>. Overall, this recipe earns an <b>amazing spoonacular score of 84%</b>. Similar recipes are <a href="https://spoonacular.com/recipes/how-sweet-it-is-sweet-potato-lasagne-1224435">How Sweet It Is Sweet Potato Lasagne</a>, <a href="https://spoonacular.com/recipes/twice-baked-sweet-potato-potato-skins-with-pecan-streusel-aka-individual-sweet-potato-casserole-247725">Twice Baked Sweet Potato Potato Skins with Pecan Streusel (akan Individual Sweet Potato Casserole)</a>, and <a href="https://spoonacular.com/recipes/twice-baked-sweet-potato-potato-skins-with-pecan-streusel-aka-individual-sweet-potato-casserole-1189579">Twice Baked Sweet Potato Potato Skins with Pecan Streusel (akan Individual Sweet Potato Casserole)</a>.',
  cuisines: ["Mediterranean", "Italian", "European"],
  dishTypes: ["lunch", "main course", "main dish", "dinner"],
  diets: ["gluten free", "lacto ovo vegetarian"],
  occasions: [],
  analyzedInstructions: [
    {
      name: "",
      steps: [
        {
          number: 1,
          step: "Slice the Sweet Potato into 1/4 inch thick slices. Boil until semi-cooked (about 10 min). Rub the slices with a dry curry powder & olive oil (1cup) mixture. Set aside and let marinate for at least 10 min.Slice Eggplants into 1/4 inch thick slices and rub all over with an olive oil (1 cup)/dried basil/salt & pepper mix. Set aside and let marinate for at least 15 min.",
          ingredients: [
            {
              id: 1102047,
              name: "salt and pepper",
              localizedName: "salt and pepper",
              image: "salt-and-pepper.jpg",
            },
            {
              id: 2015,
              name: "curry powder",
              localizedName: "curry powder",
              image: "curry-powder.jpg",
            },
            {
              id: 11507,
              name: "sweet potato",
              localizedName: "sweet potato",
              image: "sweet-potato.png",
            },
            {
              id: 2003,
              name: "dried basil",
              localizedName: "dried basil",
              image: "basil.jpg",
            },
            {
              id: 11209,
              name: "eggplant",
              localizedName: "eggplant",
              image: "eggplant.png",
            },
            {
              id: 4053,
              name: "olive oil",
              localizedName: "olive oil",
              image: "olive-oil.jpg",
            },
            {
              id: 1012034,
              name: "dry seasoning rub",
              localizedName: "dry seasoning rub",
              image: "seasoning.png",
            },
          ],
          equipment: [],
          length: {
            number: 35,
            unit: "minutes",
          },
        },
        {
          number: 2,
          step: "Pour canola or vegetable cooking oil into a pan.",
          ingredients: [
            {
              id: 4669,
              name: "vegetable oil",
              localizedName: "vegetable oil",
              image: "vegetable-oil.jpg",
            },
          ],
          equipment: [
            {
              id: 404645,
              name: "frying pan",
              localizedName: "frying pan",
              image: "pan.png",
            },
          ],
        },
        {
          number: 3,
          step: "Saute spinach and mushrooms for about 3-5 min, add in jalapenos and salt & pepper to taste.Turn the heat down and add in some heavy cream and about 1/2 of the mexican cheeses until mixture is creamy, but not watery.Start layering the lasagne in this order: Sweet Potatoes, Spinach/Mushroom",
          ingredients: [
            {
              id: 11507,
              name: "sweet potato",
              localizedName: "sweet potato",
              image: "sweet-potato.png",
            },
            {
              id: 1102047,
              name: "salt and pepper",
              localizedName: "salt and pepper",
              image: "salt-and-pepper.jpg",
            },
            {
              id: 1053,
              name: "heavy cream",
              localizedName: "heavy cream",
              image: "fluid-cream.jpg",
            },
            {
              id: 11979,
              name: "jalapeno pepper",
              localizedName: "jalapeno pepper",
              image: "jalapeno-pepper.png",
            },
            {
              id: 11260,
              name: "mushrooms",
              localizedName: "mushrooms",
              image: "mushrooms.png",
            },
            {
              id: 10011457,
              name: "spinach",
              localizedName: "spinach",
              image: "spinach.jpg",
            },
          ],
          equipment: [],
          length: {
            number: 5,
            unit: "minutes",
          },
        },
        {
          number: 4,
          step: "Mix, Eggplants, Marinara Sauce, Sweet Potatoes, Spinach/Mushrom",
          ingredients: [
            {
              id: 10111549,
              name: "marinara sauce",
              localizedName: "marinara sauce",
              image: "tomato-sauce-or-pasta-sauce.jpg",
            },
            {
              id: 11507,
              name: "sweet potato",
              localizedName: "sweet potato",
              image: "sweet-potato.png",
            },
            {
              id: 11209,
              name: "eggplant",
              localizedName: "eggplant",
              image: "eggplant.png",
            },
            {
              id: 10011457,
              name: "spinach",
              localizedName: "spinach",
              image: "spinach.jpg",
            },
          ],
          equipment: [],
        },
        {
          number: 5,
          step: "Mix, Eggplants, Then finally sprinkle the remaining Monterey Jack/Cheddar Cheese Blend on top.",
          ingredients: [
            {
              id: 1009,
              name: "cheddar cheese",
              localizedName: "cheddar cheese",
              image: "cheddar-cheese.png",
            },
            {
              id: 1001025,
              name: "monterey jack cheese",
              localizedName: "monterey jack cheese",
              image: "shredded-cheese-white.jpg",
            },
            {
              id: 11209,
              name: "eggplant",
              localizedName: "eggplant",
              image: "eggplant.png",
            },
          ],
          equipment: [],
        },
        {
          number: 6,
          step: "Bake at 350-375 for about 35-45 min, depending on how your oven works. You'll know it's ready when you can pass through a fork easily through all the layers.Devour with Passion",
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: "oven",
              localizedName: "oven",
              image: "oven.jpg",
            },
          ],
          length: {
            number: 45,
            unit: "minutes",
          },
        },
      ],
    },
  ],
  spoonacularSourceUrl:
    "https://spoonacular.com/how-sweet-it-is-sweet-potato-lasagne-647563",
  usedIngredientCount: 0,
  missedIngredientCount: 10,
  missedIngredients: [
    {
      id: 11265,
      amount: 12,
      unit: "",
      unitLong: "",
      unitShort: "",
      aisle: "Produce",
      name: "baby portabella mushrooms",
      original: "12 Baby Portabella Mushrooms, sliced",
      originalName: "Baby Portabella Mushrooms, sliced",
      meta: ["sliced"],
      image:
        "https://spoonacular.com/cdn/ingredients_100x100/portabello-mushrooms.jpg",
    },
    {
      id: 2015,
      amount: 3,
      unit: "tablespoons",
      unitLong: "tablespoons",
      unitShort: "Tbsp",
      aisle: "Spices and Seasonings",
      name: "curry powder",
      original: "3 tablespoons Dry Curry Powder",
      originalName: "Dry Curry Powder",
      meta: ["dry"],
      extendedName: "dry curry powder",
      image: "https://spoonacular.com/cdn/ingredients_100x100/curry-powder.jpg",
    },
    {
      id: 2003,
      amount: 2,
      unit: "tablespoons",
      unitLong: "tablespoons",
      unitShort: "Tbsp",
      aisle: "Spices and Seasonings",
      name: "basil leaves",
      original: "2 tablespoons Dried Basil Leaves",
      originalName: "Dried Basil Leaves",
      meta: ["dried"],
      extendedName: "dried basil leaves",
      image: "https://spoonacular.com/cdn/ingredients_100x100/basil.jpg",
    },
    {
      id: 11209,
      amount: 1,
      unit: "",
      unitLong: "",
      unitShort: "",
      aisle: "Produce",
      name: "eggplants",
      original: "1 Eggplants",
      originalName: "Eggplants",
      meta: [],
      image: "https://spoonacular.com/cdn/ingredients_100x100/eggplant.png",
    },
    {
      id: 11463,
      amount: 10,
      unit: "ounces",
      unitLong: "ounces",
      unitShort: "oz",
      aisle: "Frozen",
      name: "spinach",
      original:
        "10 ounces Frozen chopped Spinach, with excess water squeezed out",
      originalName: "Frozen chopped Spinach, with excess water squeezed out",
      meta: ["frozen", "with excess water squeezed out", "chopped"],
      extendedName: "frozen spinach",
      image:
        "https://spoonacular.com/cdn/ingredients_100x100/spinach-frozen.jpg",
    },
    {
      id: 1049,
      amount: 0.5,
      unit: "cup",
      unitLong: "cups",
      unitShort: "cup",
      aisle: "Milk, Eggs, Other Dairy",
      name: "heavy cream",
      original: "1/2 cup Half & Half or Heavy Cream",
      originalName: "Half & Half or Heavy Cream",
      meta: [],
      image: "https://spoonacular.com/cdn/ingredients_100x100/fluid-cream.jpg",
    },
    {
      id: 1001025,
      amount: 12,
      unit: "ounces",
      unitLong: "ounces",
      unitShort: "oz",
      aisle: "Cheese",
      name: "montery jack & cheddar cheese mix",
      original: "12 ounces Montery Jack & Cheddar Cheese Mix",
      originalName: "Montery Jack & Cheddar Cheese Mix",
      meta: [],
      image:
        "https://spoonacular.com/cdn/ingredients_100x100/shredded-cheese-white.jpg",
    },
    {
      id: 11979,
      amount: 2,
      unit: "",
      unitLong: "",
      unitShort: "",
      aisle: "Canned and Jarred;Produce;Ethnic Foods",
      name: "jalapenos",
      original: "2 Jalapenos, finely chopped",
      originalName: "Jalapenos, finely chopped",
      meta: ["finely chopped"],
      image:
        "https://spoonacular.com/cdn/ingredients_100x100/jalapeno-pepper.png",
    },
    {
      id: 10111549,
      amount: 3,
      unit: "cups",
      unitLong: "cups",
      unitShort: "cup",
      aisle: "Pasta and Rice",
      name: "marinara sauce",
      original:
        "3 cups Marinara Sauce (home made or a jar of 24 oz store bought)",
      originalName: "Marinara Sauce (home made or a jar of 24 oz store bought)",
      meta: ["store bought", "(home made or a jar of 24 oz )"],
      image:
        "https://spoonacular.com/cdn/ingredients_100x100/tomato-sauce-or-pasta-sauce.jpg",
    },
    {
      id: 11507,
      amount: 4,
      unit: "",
      unitLong: "",
      unitShort: "",
      aisle: "Produce",
      name: "sweet potatoes",
      original: "4 Sweet Potatoes",
      originalName: "Sweet Potatoes",
      meta: [],
      image: "https://spoonacular.com/cdn/ingredients_100x100/sweet-potato.png",
    },
  ],
  likes: 0,
  usedIngredients: [],
  unusedIngredients: [],
  nutrition: {
    nutrients: [
      {
        name: "Calories",
        amount: 500.872,
        unit: "kcal",
      },
    ],
  },
};

//   {
//     id: 782585,
//     title: "Cannellini Bean and Asparagus Salad with Mushrooms",
//     image: "https://spoonacular.com/recipeImages/782585-312x231.jpg",
//     extendedIngredients: [
//       {
//         id: 1,
//         name: "cannellini beans",
//       },
//       {
//         id: 2,
//         name: "curry leaves",
//       },
//       {
//         id: 3,
//         name: "tarragon",
//       },
//       {
//         id: 4,
//         name: "garlic",
//       },
//       {
//         id: 5,
//         name: "juice of lemon",
//       },
//       {
//         id: 6,
//         name: "lemon zest",
//       },
//       {
//         id: 4053,
//         name: "olive oil",
//       },
//       {
//         id: 4053,
//         name: "olive oil",
//       },
//       {
//         id: 7,
//         name: "sea salt",
//       },
//       {
//         id: 8,
//         name: "cracked pepper",
//       },
//       {
//         id: 9,
//         name: "mushrooms",
//       },
//       {
//         id: 10,
//         name: "grain mustard",
//       },
//     ],
//     // summary: `Cannellini Bean and Asparagus Salad with Mushrooms requires approximately <b>45 minutes</b> from start to finish. This main course has <b>482 calories</b>, <b>31g of protein</b>, and <b>6g of fat</b> per serving. This gluten free, dairy free, lacto ovo vegetarian, and vegan recipe serves 6 and costs <b>$1.35 per serving</b>. 309 people were impressed by this recipe. Head to the store and pick up grain mustard, sea salt, lemon zest, and a few other things to make it today. It is brought to you by foodandspice.blogspot.com. Taking all factors into account, this recipe <b>earns a spoonacular score of 70%</b>, which is pretty good. Similar recipes are <a href="https://spoonacular.com/recipescannellini-bean-salad-422994">Cannellini Bean Salad</a>, <a href="https://spoonacular.com/recipesrefreshing-cannellini-bean-salad-113127">Refreshing Cannellini Bean Salad</a>, and <a href="https://spoonacular.com/recipes/cannellini-and-green-bean-salad-33177">Cannellini-and-Green Bean Salad</a>.`,
//     dishTypes: [
//       "side dish",
//       "lunch",
//       "main course",
//       "salad",
//       "main dish",
//       "dinner",
//     ],
//   },
//   {
//     id: 716426,
//     title: "Cauliflower, Brown Rice, and Vegetable Fried Rice",
//     image: "https://spoonacular.com/recipeImages/716426-312x231.jpg",
//     summary: `You can never have too many Chinese recipes, so give Cauliflower, Brown Rice, and Vegetable Fried Rice a try. This recipe serves 8 and costs $1.12 per serving. This hor d'oeuvre has <b>192 calories</b>, <b>7g of protein</b>, and <b>6g of fat</b> per serving. Head to the store and pick up broccoli, sesame seeds, soy sauce, and a few other things to make it today. 3689 people were impressed by this recipe. It is brought to you by fullbellysisters.blogspot.com. It is a good option if you're following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. From preparation to the plate, this recipe takes roughly <b>30 minutes</b>. Overall, this recipe earns a <b>spectacular spoonacular score of 100%</b>. If you like this recipe, you might also like recipes such as <a href="https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-1584601">Cauliflower, Brown Rice, and Vegetable Fried Rice</a>, <a href="https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-1238897">Cauliflower, Brown Rice, and Vegetable Fried Rice</a>, and <a href="https://spoonacular.com/recipes/cauliflower-brown-rice-and-vegetable-fried-rice-1230097">Cauliflower, Brown Rice, and Vegetable Fried Rice</a>.`,
//     dishTypes: [
//       "side dish",
//       "antipasti",
//       "starter",
//       "snack",
//       "appetizer",
//       "antipasto",
//       "hor d'oeuvre",
//     ],
//   },
//   {
//     id: 716406,
//     title: "Asparagus and Pea Soup: Real Convenience Food",
//     // image: "https://spoonacular.com/recipeImages/716406-312x231.jpg",
//     summary: `Asparagus and Pea Soup: Real Convenience Food requires approximately <b>20 minutes</b> from start to finish. Watching your figure? This gluten free, dairy free, paleolithic, and lacto ovo vegetarian recipe has <b>217 calories</b>, <b>11g of protein</b>, and <b>8g of fat</b> per serving. This recipe serves 2. For <b>$1.78 per serving</b>, this recipe <b>covers 25%</b> of your daily requirements of vitamins and minerals. <b>Autumn</b> will be even more special with this recipe. It works well as a hor d'oeuvre. 207 people have tried and liked this recipe. It is brought to you by fullbellysisters.blogspot.com. A mixture of vegetable broth, evoo, garlic, and a handful of other ingredients are all it takes to make this recipe so yummy. All things considered, we decided this recipe <b>deserves a spoonacular score of 96%</b>. This score is outstanding. Try <a href="https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-1393979">Asparagus and Pea Soup: Real Convenience Food</a>, <a href="https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-1376201">Asparagus and Pea Soup: Real Convenience Food</a>, and <a href="https://spoonacular.com/recipes/asparagus-and-pea-soup-real-convenience-food-1362341">Asparagus and Pea Soup: Real Convenience Food</a> for similar recipes.`,
//     dishTypes: [
//       "antipasti",
//       "soup",
//       "starter",
//       "snack",
//       "appetizer",
//       "antipasto",
//       "hor d'oeuvre",
//     ],
//   },
// ];

export default data;
